### ISSUE TITLE
Deleting Remote BigWig File Results in Error

### ISSUE THREAD

**Issue by sonnyarora** [higlass/higlass-server#145]
Running higlass-server on CentOS7. To replicate:

```
python higlass-server/manage.py ingest_tileset --filename http://127.0.0.1/api/v1/tracks/test.bw --no-upload --filetype bigwig --coordSystem mm10 --uid test
```
Seems to work fine, I can load the file in HiGlass. Running:

```
python higlass-server/manage.py delete_tileset --uuid test
```
Gives the error:
```
Command Error: File does not exist under media root
```
Let me know if you need any more information from me. Thanks in advance!

**Comment by pkerpedjiev** [comment]
Hey, sorry for the delayed response but are you using `simple-httpfs` to mount the `media/http` directory?

When I run the ingest command I get the following:

```
(base) toc2~/projects/higlass-server(master|✔) % python manage.py ingest_tileset --filename http://127.0.0.1/api/v1/tracks/test.bw --no-upload --filetype bigwig --coordSystem mm10 --uid test
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/pete/miniconda3/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/pete/miniconda3/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/pete/miniconda3/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/pete/miniconda3/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/Users/pete/projects/higlass-server/tilesets/management/commands/ingest_tileset.py", line 236, in handle
    ingest(**options)
  File "/Users/pete/projects/higlass-server/tilesets/management/commands/ingest_tileset.py", line 90, in ingest
    coordSystem = check_for_chromsizes(filename, coordSystem)
  File "/Users/pete/projects/higlass-server/tilesets/management/commands/ingest_tileset.py", line 127, in check_for_chromsizes
    tileset_info = hgbi.tileset_info(filename)
  File "/Users/pete/miniconda3/lib/python3.8/site-packages/clodius/tiles/bigwig.py", line 65, in tileset_info
    chromsizes = get_chromsizes(bwpath)
  File "/Users/pete/miniconda3/lib/python3.8/site-packages/clodius/tiles/bigwig.py", line 37, in get_chromsizes
    chromsizes = bbi.chromsizes(bwpath)
  File "bbi/cbbi.pyx", line 152, in bbi.cbbi.chromsizes
  File "bbi/cbbi.pyx", line 54, in bbi.cbbi._check_sig
  File "bbi/cbbi.pyx", line 39, in bbi.cbbi._read_magic
OSError: File not found: /Users/pete/projects/higlass-server/media/http/127.0.0.1/api/v1/tracks/test.bw..
```

**Comment by sonnyarora** [comment]
Hi Pete,

Sorry I didn't mention it, I am using simple-httpfs to mount the directory.

**Comment by pkerpedjiev** [comment]
Would you mind trying the `delete_urls` branch? I created a PR that I'm pretty sure fixes this issue here: https://github.com/higlass/higlass-server/pull/149
